w5 arithmetic_dragons
TrinhVanDuc/Holy pull request #4
Opened 2020-10-19 10:16 UTC by TrinhVanDuc

2020-10-20 12:17 UTC, alekseik1 requested changes
Не работает:
```python
(base) ➜  arithmetic_dragons git:(dragons) ✗ python main.py
__main__
Добро пожаловать в арифметико-ролевую игру с драконами!
Представьтесь, пожалуйста: 1
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    start_game()
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/tournament.py", line 69, in start_game
    dragon_list = generate_dragon_list(dragon_number)
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/enemies.py", line 17, in generate_dragon_list
    enemy_list = [generate_random_enemy() for i in range(enemy_number)]
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/enemies.py", line 17, in <listcomp>
    enemy_list = [generate_random_enemy() for i in range(enemy_number)]
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/enemies.py", line 11, in generate_random_enemy
    RandomEnemyType = choice(enemy_types)
NameError: name 'choice' is not defined
```

2020-10-20 12:17 UTC, alekseik1 commented on arithmetic_dragons/enemies.py
> +    RandomEnemyType = choice(enemy_types)
Названия переменных лучше давать в camel_case стиле

2020-10-20 12:17 UTC, alekseik1 commented on arithmetic_dragons/hero.py
> +#FIXME:
`FIXME` можно убрать, раз ты уже все сделал

2020-10-21 19:18 UTC, TrinhVanDuc commented
Здравствуйте! Были некоторые ошибки, и я их исправил.

2020-10-21 19:49 UTC, alekseik1 commented
Снова не работает:

2020-10-21 20:03 UTC, TrinhVanDuc commented
О да, я исприл ещё раз. Теперь я думаю все хорошо)

2020-10-21 20:08 UTC, alekseik1 requested changes
Нет, все еще падает:
```python
(base) ➜  arithmetic_dragons git:(dragons) ✗ python main.py
__main__
Добро пожаловать в арифметико-ролевую игру с драконами!
Представьтесь, пожалуйста: 123
У Вас на пути 3 драконов!
Вышел зелёный дракон!
Вопрос: 70+63
Ответ:133
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    start_game()
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/tournament.py", line 72, in start_game
    game_tournament1(hero, dragon_list)
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/tournament.py", line 24, in game_tournament1
    hero.attack(dragon)
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/hero.py", line 11, in attack
    Hero += 1
UnboundLocalError: local variable 'Hero' referenced before assignment
```

Исправь, пожалуйста, **все** ошибки, запусти у себя несколько раз и убедись, что все работает. А потом уже отправляй на проверку, хорошо?

2020-10-21 20:11 UTC, TrinhVanDuc commented
Да, я понял.

2020-10-25 14:14 UTC, alekseik1 commented
Ответ:589
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    start_game()
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/tournament.py", line 75, in start_game
    game_tournament1(hero, dragon_list)
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/tournament.py", line 24, in game_tournament1
    hero.attack(dragon)
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/hero.py", line 11, in attack
    Hero._experience += 1
AttributeError: type object 'Hero' has no attribute '_experience'

2020-10-26 19:13 UTC, alekseik1 commented
Все равно есть ошибки:
```python
Вопрос: 59+64
Ответ:123
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    start_game()
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/tournament.py", line 75, in start_game
    game_tournament1(hero, dragon_list)
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/tournament.py", line 24, in game_tournament1
    hero.attack(dragon)
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/hero.py", line 11, in attack
    target._experience += 1
AttributeError: 'GreenDragon' object has no attribute '_experience'
```

а также то же самое:
```python
Ответ:1995
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    start_game()
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/tournament.py", line 75, in start_game
    game_tournament1(hero, dragon_list)
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/tournament.py", line 24, in game_tournament1
    hero.attack(dragon)
  File "/Users/a.kozharin/kids/chin-van-dik/arithmetic_dragons/hero.py", line 11, in attack
    target._experience += 1
AttributeError: 'BlackDragon' object has no attribute '_experience'
```

2020-10-31 08:36 UTC, alekseik1 commented
1. В конце дает 0 опыта
2. Игра начинается заново сразу после окончания.

В целом, все хорошо. 8/10

2020-10-31 08:37 UTC, merged