W6
TrinhVanDuc/Holy pull request #5
Opened 2020-10-26 10:09 UTC by TrinhVanDuc

2020-10-26 19:08 UTC, alekseik1 requested changes
1. Лучше все `.idea/` файлы убрать из Git и добавить в `.gitignore`. Погугли "How to remove .idea folder from git"
2. Еще есть комментарии в коде.

2020-10-26 19:08 UTC, alekseik1 commented on w6/Задача_3+4+5_.py
> +    def complex(cls):
Нельзя переопределять `complex()` в `MyComplexMath`.

Для этого нужно исправить `__complex`, заменив на `_complex`. Это нужно сделать в родительском классе и дочернем классе

2020-10-26 19:08 UTC, alekseik1 commented on w6/Задача_6.py
> +import math
Нет класса `Complex`

2020-10-26 19:32 UTC, TrinhVanDuc commented
я их уже исправил

2020-10-31 08:39 UTC, alekseik1 approved these changes
Ок, 16/16

2020-10-31 08:39 UTC, merged