W7
TrinhVanDuc/Holy pull request #6
Opened 2020-11-02 09:17 UTC by TrinhVanDuc

2020-11-02 09:42 UTC, alekseik1 requested changes
1. Нет файла `requirements.txt` в корне проекта.
2. Тесты не проходят:
```python
(venv) (base) ➜  w7 git:(w7) ✗ python -m pytest
============================= test session starts ==============================
platform darwin -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/a.kozharin/kids/chin-van-dik/w7
collected 7 items

test_my_math.py ...F...                                                  [100%]

=================================== FAILURES ===================================
________________________________ test_dictance _________________________________

    def test_dictance():
        x1 = Vector(1,2,3)
>       assert x1.dictances() == np.linalg.norm([1,2,3])
E       AssertionError: assert 1.0 == 3.7416573867739413
E        +  where 1.0 = <bound method Vector.dictances of <my_mathematics.linear_algebra.Vector object at 0x125668940>>()
E        +    where <bound method Vector.dictances of <my_mathematics.linear_algebra.Vector object at 0x125668940>> = <my_mathematics.linear_algebra.Vector object at 0x125668940>.dictances
E        +  and   3.7416573867739413 = <function norm at 0x108f358b0>([1, 2, 3])
E        +    where <function norm at 0x108f358b0> = <module 'numpy.linalg' from '/Users/a.kozharin/kids/chin-van-dik/w7/venv/lib/python3.8/site-packages/numpy/linalg/__init__.py'>.norm
E        +      where <module 'numpy.linalg' from '/Users/a.kozharin/kids/chin-van-dik/w7/venv/lib/python3.8/site-packages/numpy/linalg/__init__.py'> = np.linalg

test_my_math.py:21: AssertionError
=========================== short test summary info ============================
FAILED test_my_math.py::test_dictance - AssertionError: assert 1.0 == 3.74165...
========================= 1 failed, 6 passed in 3.43s ==========================
```

3. Тесты надо положить в папку `tests/`. Также следует использовать фикстуры в тестах.

2020-11-02 11:54 UTC, TrinhVanDuc commented
Добрый день! Я уже исправил мои ошибки и добваил фалу requirements.txt.

2020-11-03 18:22 UTC, alekseik1 requested changes
1. В `requirements.txt` следует писать только название пакетов, по одному на строку. Например,
```bash
numpy
pandas
pytest
```

2. В будущем стоит писать тесты через фикстуры и параметризацию. Об этом можно почитать здесь: [параметризация](https://docs.pytest.org/en/stable/parametrize.html), [фикстуры](https://docs.pytest.org/en/stable/fixture.html)

2020-11-05 09:25 UTC, TrinhVanDuc commented
Здравствуйте! файлу я уже исправил

2020-11-08 12:50 UTC, merged

2020-11-08 12:50 UTC, alekseik1 commented
ок, 14/15