W8
TrinhVanDuc/Holy pull request #7
Opened 2020-11-08 20:18 UTC by TrinhVanDuc

2020-11-14 11:05 UTC, alekseik1 requested changes
Оставил комментарии к коду
21/36

2020-11-14 11:05 UTC, alekseik1 commented on w8/tests/test_4.py
> +@pytest.mark.parametrize('n,result',[(get_cartesian_product([1, 2], [3, 4]),[(1, 3), (1, 4), (2, 3), (2, 4)])])
В параметризации лучше указывать только входные данные, а функцию вызывать внутри теста. Конкретно этот тест можно было бы записать так:
```python
@pytest.mark.parametrize('func_args, result', [
    [([1, 2], [3, 4]), [(1, 3), (1, 4), (2, 3), (2, 4)]],
])
def test_product(func_args, result):
    assert get_cartesian_product(*func_args) == result
```
Аналогично с остальными фикстурами

2020-11-14 11:05 UTC, alekseik1 commented on w8/tests/test_5.py
> +@pytest.mark.parametrize('in_put,result',[(get_permutations("cat", 2), ["ac", "at", "ca", "ct", "ta", "tc"])])
Аналогично тесту 4

2020-11-14 11:05 UTC, alekseik1 commented on w8/tests/test_6.py
> +@pytest.mark.parametrize('in_put, result',[(get_combinations('cat',2),["a", "c", "t", "ac", "at", "ct"])])
Аналогично тесту 4

2020-11-14 11:05 UTC, alekseik1 commented on w8/tests/test_7.py
> +@pytest.mark.parametrize('in_put, result', [(get_combinations_with_r("cat", 2), ["aa", "ac", "at", "cc", "ct", "tt"])])
Аналогично тесту 4

2020-11-14 11:05 UTC, alekseik1 commented on w8/tests/test_8.py
> +@pytest.mark.parametrize('in_put, result',[(compress_string('1222311'), [(1, 1), (3, 2), (1, 3), (2, 1)])])
Аналогично тесту 4

2020-11-14 11:05 UTC, alekseik1 commented on w8/tests/test_9.py
> +@pytest.mark.parametrize('in_put, result',[(maximize(lists, m=1000), 206)])
Аналогично тесту 4

2020-11-14 11:05 UTC, alekseik1 commented on w8/homework/Задача_3.py
> +abs_values = list(map(abs, numbers))
Тут нужно самим написать свой собственный `zip`, `map`, `enumerate`. Встроенными функциями пользоваться нельзя

2020-11-14 11:05 UTC, alekseik1 commented on w8/homework/Задача_4.py
> +        return list(itertools.product(a,b))
Не нужно преобразовывать к `list` - тогда у тебя не будут все элементы сразу подсчитываться. Мы как раз и хотим этого достичь: получать данные "на лету", по мере необходимости

2020-11-14 11:05 UTC, alekseik1 commented on w8/homework/Задача_5.py
> +        return sorted(list(''.join(i) for i in itertools.permutations(s,n)))
Аналогично задаче 4, нельзя использовать `list`, потому что в этом случае все элементы считаются сразу, а не на лету

2020-11-14 11:05 UTC, alekseik1 commented on w8/homework/Задача_6.py
> +        list_combinations = sorted(list(''.join(sorted(x)) for i in range(1,n+1) for x in itertools.combinations(s,i)))
Аналогично задаче 4, нельзя использовать list, потому что в этом случае все элементы считаются сразу, а не на лету

2020-11-14 11:05 UTC, alekseik1 commented on w8/homework/Задача_7.py
> +        return sorted(list(''.join(sorted(i)) for i in itertools.combinations_with_replacement(s,n)))
Аналогично задаче 4, нельзя использовать list, потому что в этом случае все элементы считаются сразу, а не на лету

2020-11-14 11:05 UTC, alekseik1 commented on w8/homework/Задача_8.py
> +        return list(zip(c,b))
Не нужно использовать `list()`, пусть возвращает генератор

2020-11-16 10:54 UTC, TrinhVanDuc commented
Здравствуйте! я уже исправил ошибки.

2020-11-22 19:22 UTC, alekseik1 commented
Падают тесты:
```python
_______________________ ERROR collecting tests/test_9.py _______________________
ImportError while importing test module '/Users/a.kozharin/kids/chin-van-dik/w8/tests/test_9.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_9.py:1: in <module>
    from homework.Задача_9 import maximize
E   ModuleNotFoundError: No module named 'homework'
```
Это легко исправить: переименуй, пожалуйста, папку `homeworks/` в `homework/`

2020-11-22 19:22 UTC, alekseik1 approved these changes
Сделай Merge request, как только исправишь тесты, ок?

2020-11-22 19:43 UTC, TrinhVanDuc commented
Да! Я запутался между homework и homeworks.

2020-11-22 20:59 UTC, alekseik1 approved these changes
Теперь все в порядке.
36/36

2020-11-22 20:59 UTC, merged